version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000" # API Server
      - "5001:5001" # gRPC Server
    environment:
      - MINIO_ENDPOINT=minio1:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - minio1
      - minio2
      - minio3

  minio1:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9091:9090"
    volumes:
      - minio_data1:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" http://minio{1...3}/data

  minio2:
    image: minio/minio
    ports:
      - "9002:9000"
      - "9092:9090"
    volumes:
      - minio_data2:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" http://minio{1...3}/data

  minio3:
    image: minio/minio
    ports:
      - "9003:9000"
      - "9093:9090"
    volumes:
      - minio_data3:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" http://minio{1...3}/data

volumes:
  minio_data1:
  minio_data2:
  minio_data3:
